version: 2

models:
# Daily time spine
  - name: all_dates
    description: scaffold of all days since 2020-01-01
    time_spine:
      standard_granularity_column: date_day # column for the standard grain of your table
    columns:
      - name: date_day
        granularity: day # set granularity at column-level for standard_granularity_column
    config:
      materialized: table